DROP TABLE IF EXISTS MERCHANT;
create table MERCHANT
(
    CD_MERCHANT VARCHAR2(14),
    NM_TRADE_NAME VARCHAR2(50),
    NU_DOCUMENT   VARCHAR2(14),
    CD_DOCUMENT_TYPE NUMBER,
    DT_REGISTRATION  VARCHAR2(14),
    HR_REGISTRATION  VARCHAR2(14),
    NM_CONTACT_FULL_NAME VARCHAR2(100),
    NU_CONTACT_DOCUMENT  VARCHAR2(14),
    CD_CONTACT_DOCUMENT_TYPE NUMBER,
    CD_CONTACT_TYPE VARCHAR2(2),
    DS_ADDRESS VARCHAR2(250),
    CD_ZIP_CODE NUMBER,
    CD_CITY_TYPE VARCHAR2(15)
);